In [1]:
import numpy as np

# np.random shuffle 이란 리스트 안의 배열을 무작위로 섞는 함수

In [2]:
A = np.array([ data for data in range(6)  ])

print(A)
print(type(A), A.shape)

[0 1 2 3 4 5]
<class 'numpy.ndarray'> (6,)


In [3]:
np.random.shuffle(A)

print(A)
print(type(A), A.shape)

[4 0 1 3 5 2]
<class 'numpy.ndarray'> (6,)


In [4]:
B = np.array([ [data, data] for data in range(4) ])

print(B)
print(type(B), B.shape)

[[0 0]
 [1 1]
 [2 2]
 [3 3]]
<class 'numpy.ndarray'> (4, 2)


In [5]:
np.random.shuffle(B)

print(B)
print(type(B), B.shape)

[[1 1]
 [3 3]
 [0 0]
 [2 2]]
<class 'numpy.ndarray'> (4, 2)


In [ ]:
# 하는 이유 : traing과 test 데이터의 다양하게 섞어서 분리하기 위해