정확도가 낮은이유
가중치의 random 떄문
예측범위 내의 가중치의 다양성 필요(정규분포)
- xavier/he
표준화 표준편차가 1이고 평균이 0으로 만드는것
표준편차란 평균과의 차이가 얼마인지

평균이 50일떄
(50, 49, 51, 50)
(100, 0, 0, 100) 둘다 평균 50
표준편차가 1이고 평균이 0이라는것은 데이터가 대칭으로 되있다는것

one hot 되있는 출력값을 소프트맥스에 집어넣는다
시그모이드가 y값을 계산하는것이 아닌 SM가 y값을 계산한다

자기자신 / 전체 노드수 => 확률로도 해석됨

하나하나의 노드가 나타낼수 있는 확률
시그모이드를 사용하지않고 그 뒤에 붙임
해석의 문제
softmax 는 확률적인 부분을 보여주는것이기에 해석의 문제이다


In [2]:
import numpy as np

In [12]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y 

    
A = np.array([0.7, 0.8, 0.01])
B = np.array([0.3, 2.9, 4.0])
C = np.array([110, 100, 90])
D = np.array([1000, 1100, 900])    

print(softmax(A))
print(softmax(B))
print(softmax(C))
print(softmax(D))
# 큰값의 무한대로의 발생을 막기 위해서  함수의 최댓값에서 뺴준다

[0.38361989 0.42396555 0.19241456]
[0.01821127 0.24519181 0.73659691]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]
[3.72007598e-44 1.00000000e+00 1.38389653e-87]
